// -------------------------------------------------------------------------------------------------
// <auto-generated>    
//  Marked as auto-generated so StyleCop will ignore BDD style tests
// </auto-generated>
// -------------------------------------------------------------------------------------------------
namespace Leatn.Web.Controllers.RSS.Mappers
{
    using System.Collections.Generic;

    using Contracts;

    using Domain.Blog.BlogPost;

    using Machine.Specifications;
    using Machine.Specifications.AutoMocking.Rhino;
    using Machine.Specifications.Utility;

    using Rhino.Mocks;

    using ViewModels;

    public abstract class context_for_rss_feed_view_model_mapper : Specification<RSSFeedViewModelMapper>
    {
        protected static IRSSElementViewModelMapper rss_element_view_model_mappper;

        Establish context = () =>
            {
                rss_element_view_model_mappper = DependencyOf<IRSSElementViewModelMapper>();
            };
    }

    public class when_the_rss_feed_view_model_mapper_is_asked_to_map_from_the_latest_blogs : context_for_rss_feed_view_model_mapper
    {
        static IEnumerable<BlogPost> the_latest_blog_posts;

        static RSSFeedViewModel the_model;

        Establish context = () =>
            {
                the_latest_blog_posts = new List<BlogPost> { new BlogPost() };
            };

        Because of = () =>
            {
                the_model = subject.MapFrom(the_latest_blog_posts);
            };

       // It should_ask_the_rss_element_mapper_to_map_the_elements_from_the_latest_blog_posts = () => the_latest_blog_posts.Each(x => rss_element_view_model_mappper.AssertWasCalled(m => m.MapFrom(x)));
    }
}