// -------------------------------------------------------------------------------------------------
// <auto-generated>    
//  Marked as auto-generated so StyleCop will ignore BDD style tests
// </auto-generated>
// -------------------------------------------------------------------------------------------------
namespace Leatn.Web.Controllers.Search.Mappers
{
    using Contracts;

    using Domain.Blog;
    using Domain.Blog.BlogPost;
    using Domain.Contracts.Repositories;
    using Domain.Contracts.Specifications;
    using Domain.Shared;

    using Framework.Contracts.Specifications;

    using Machine.Specifications;
    using Machine.Specifications.AutoMocking.Rhino;

    using Rhino.Mocks;

    using Tasks.Factories.Contracts;

    using ViewModels;

    public abstract class context_for_search_result_view_model_mapper : Specification<SearchResultViewModelMapper>
    {
        protected static IBlogPostSpecificationFactory blog_post_specification_factory;

        protected static IBlogPostRepository blog_post_repository;

        Establish context = () =>
            {
                blog_post_specification_factory = DependencyOf<IBlogPostSpecificationFactory>();
                blog_post_repository = DependencyOf<IBlogPostRepository>();
            };
    }

    public class when_the_search_result_view_model_mapper_is_asked_to_map_from_a_blog : context_for_search_result_view_model_mapper
    {
        static Domain.Blog.Blog the_blog;

        static string the_blog_url;

        static SearchResultViewModel the_search_result_view_model;

        Establish context = () =>
            {
                the_blog_url = "new blog";

                the_blog = new Blog { Url = the_blog_url };
            };

        Because of =()=>
            {
                the_search_result_view_model = subject.MapFrom(the_blog);
            };

        It should_map_the_url_correctly =()=> the_search_result_view_model.Url.ShouldEqual(the_blog_url);

    }

    public class when_the_search_result_view_model_mapper_is_asked_to_map_from_a_blog_post : context_for_search_result_view_model_mapper
    {
        static string the_blog_post_url;

        static BlogPost the_blog_post;

        static SearchResultViewModel the_search_result_view_model;

        static ILinqSpecification<BlogPost> the_blog_post_url_specification;
        
        static string the_blog_url;

        static Blog the_blog;

        Establish context = () =>
            {
                the_blog_post_url_specification = new AdHocSpecification<BlogPost>(x => true);

                the_blog_post_url = "blog-post-one";

                blog_post_specification_factory.Stub(x => x.GetUrlSpecification(the_blog_post_url)).Return(
                    the_blog_post_url_specification);

                the_blog_url = "blog_url";

                the_blog = new Blog
                    {
                        Url = the_blog_url
                    };

                the_blog_post = new BlogPost
                    {
                        Url = the_blog_post_url,
                        Blog = the_blog
                    };

                blog_post_repository.Stub(x => x.FindOne(the_blog_post_url_specification)).Return(the_blog_post);
            };

        Because of =()=>
            {
                the_search_result_view_model = subject.MapFrom(the_blog_post);
            };
        
        It should_ask_the_blog_post_specification_factory_for_the_url_specification =()=> blog_post_specification_factory.AssertWasCalled(x=>x.GetUrlSpecification(the_blog_post_url));
        It should_ask_the_blog_post_repository_for_the_blog_post = ()=> blog_post_repository.AssertWasCalled(x=>x.FindOne(the_blog_post_url_specification));
        It should_map_the_blog_url_correctly =() => the_search_result_view_model.BlogUrl.ShouldEqual(the_blog_url);
        It should_map_the_blog_post_url_correctly = () =>the_search_result_view_model.Url.ShouldEqual(the_blog_post_url);

    }
}