// -------------------------------------------------------------------------------------------------
// <auto-generated>    
//  Marked as auto-generated so StyleCop will ignore BDD style tests
// </auto-generated>
// -------------------------------------------------------------------------------------------------
namespace Leatn.Web.Controllers.Shared.Mappers
{
    #region Using Directives

    using System.Collections.Generic;

    using Contracts;

    using Domain.Blog;

    using Machine.Specifications;
    using Machine.Specifications.AutoMocking.Rhino;

    using Rhino.Mocks;

    using ViewModels;

    #endregion

    public abstract class context_for_archive_year_view_model_mapper : Specification<ArchiveYearViewModelMapper>
    {
        protected static IArchiveMonthsViewModelMapper archive_months_view_model_mapper;

        Establish context = () =>
            {
                archive_months_view_model_mapper = DependencyOf<IArchiveMonthsViewModelMapper>();
            };
    }

    public class when_the_archive_year_view_model_mapper_is_asked_to_map_from_some_blog_posts_and_a_year : context_for_archive_year_view_model_mapper
    {
        static ArchiveYearViewModel the_mapped_archive_year_view_model;

        static Blog the_blog;

        static string the_blog_url;

        static int the_archive_year;

        static IEnumerable<int> the_archive_months;

        Establish context = () =>
            {
                the_blog_url = "new blog";

                the_blog = new Blog { Url = the_blog_url };

                the_archive_year = 2010;

                the_archive_months = new List<int>();

            };

        Because of = () =>
            {
                the_mapped_archive_year_view_model = subject.MapFrom(the_blog, the_archive_year);
            };

        It should_map_the_blog_url_correctly = () => the_mapped_archive_year_view_model.BlogUrl.ShouldEqual(the_blog_url);

        It should_map_the_archive_year_correctly = () => the_mapped_archive_year_view_model.ArchiveYear.ShouldEqual(the_archive_year);

    }
}