// -------------------------------------------------------------------------------------------------
// <auto-generated>    
//  Marked as auto-generated so StyleCop will ignore BDD style tests
// </auto-generated>
// -------------------------------------------------------------------------------------------------
namespace Leatn.Web.Mvc.UI.Components.Matrix.Mappers
{
    using Machine.Specifications;
    using Machine.Specifications.AutoMocking.Rhino;

    using Models;

    public abstract class context_for_cell_mapper : Specification<CellMapper<TestModel>>
    {

    }

    public class when_the_cell_mapper_is_asked_to_map_from_a_model : context_for_cell_mapper
    {
        static Cell<TestModel> the_mapped_cell;

        static TestModel the_model;

        Establish context = () =>
            {
                the_model = new TestModel();
            };
        
        Because of =()=>
            {
                the_mapped_cell = subject.MapFrom(the_model);
            };

        It should_return_a_cell_containing_the_model = () => the_mapped_cell.Model.ShouldBeTheSameAs(the_model);
    }
}