// -------------------------------------------------------------------------------------------------
// <auto-generated>    
//  Marked as auto-generated so StyleCop will ignore BDD style tests
// </auto-generated>
// -------------------------------------------------------------------------------------------------
namespace Leatn.Web.Controllers.RSS
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;

    using Domain.Blog.BlogPost;
    using Domain.Contracts.Tasks;

    using Machine.Specifications;
    using Machine.Specifications.AutoMocking.Rhino;
    using Machine.Specifications.Mvc;

    using Mappers.Contracts;

    using Rhino.Mocks;

    using Shared.ActionResults;

    using ViewModels;

    public abstract class context_for_rss_controller : Specification<RSSController>
    {
        protected static IBlogPostTasks blog_post_tasks;

        protected static IRSSFeedViewModelMapper rss_feed_view_model_mapper;


        Establish context = () =>
            {
                blog_post_tasks = DependencyOf<IBlogPostTasks>();
                rss_feed_view_model_mapper = DependencyOf<IRSSFeedViewModelMapper>();
            };
    }

    public class when_the_rss_controller_is_asked_for_the_feed : context_for_rss_controller
    {
        static ActionResult result;
        static RSSFeedViewModel the_rss_feed_view_model;
        static IQueryable<BlogPost> the_latest_blog_posts;

        Establish context = () =>
            {
                the_latest_blog_posts = new List<BlogPost>().AsQueryable();
                blog_post_tasks.Stub(x => x.GetLatestBlogPosts()).Return(the_latest_blog_posts);

                the_rss_feed_view_model = new RSSFeedViewModel();
                rss_feed_view_model_mapper.Stub(x => x.MapFrom(the_latest_blog_posts)).Return(the_rss_feed_view_model);
            };

        Because of = () =>
            {
                result = subject.Feed();
            };

        It should_ask_the_blog_post_tasks_for_the_lates_blog_posts = () => blog_post_tasks.AssertWasCalled(x => x.GetLatestBlogPosts());
        It should_ask_the_rss_feed_view_model_mapper_to_map_from_the_lates_blog_posts =()=> rss_feed_view_model_mapper.AssertWasCalled(x=>x.MapFrom(the_latest_blog_posts));
      //  It should_return_the_rss_feed_view_model_the_view = () => result.Model<RSSFeedViewModel>().ShouldBeTheSameAs(the_rss_feed_view_model);
    }
}