// -------------------------------------------------------------------------------------------------
// <auto-generated>    
//  Marked as auto-generated so StyleCop will ignore BDD style tests
// </auto-generated>
// -------------------------------------------------------------------------------------------------
namespace Leatn.Web.Mvc.UI.Components.Matrix.Renderers
{
    using System.IO;
    using System.Web.Mvc;

    using Components.Contracts;

    using Machine.Specifications;
    using Machine.Specifications.AutoMocking.Rhino;

    using Models;

    public abstract class context_for_cell_renderer : Specification<CellRenderer<TestModel>>
    {
        protected static IComponentOutput component_output;

        Establish context = () =>
        {
            component_output = new ComponentOutput(new ViewContext(), new StringWriter());
            ProvideBasicConstructorArgument(component_output);
        };
    }

    public class when_cell_renderer_is_asked_to_render_start_tag : context_for_cell_renderer
    {
        Because of = () => subject.RenderStartTag();

        It should_render_an_html_table_cell_opening_tag = () => component_output.Writer.ToString().ShouldEqual("\r\n<td>");
    }

    public class when_cell_renderer_is_asked_to_render_end_tag : context_for_cell_renderer
    {
        Because of = () => subject.RenderEndTag();

        It should_render_an_html_table_cell_closing_tag = () => component_output.Writer.ToString().ShouldEqual("\r\n</td>");
    }

    public class when_cell_renderer_is_asked_to_render_cell : context_for_cell_renderer
    {
        static Cell<TestModel> the_cell;

        Establish context = () =>
        {
            the_cell = new Cell<TestModel>(new TestModel { Name = "testItem1" });
        };

        Because of = () => subject.RenderCell(the_cell);

        //It should_ask_the_row_renderer_to_render_the_rows_on_the_matrix_model = () => );
    }
}